### ISSUE TITLE
Project 6 - Mongoose find() and countDocuments() no longer accept callbacks

### ISSUE THREAD

**Issue by ItalianJack** [btdobbs/WA#6]
After project 6 is setup, the two test links to `/test/info` and `/test/counts` throw errors that Model.find() and Model.countDocuments() methods no longer accept callbacks. The test pages display these errors. These methods are called from webServer.js lines 76 and 106, respectively. Logs below: 

<details><summary>Details</summary>
<p>

```
"C:\Program Files\nodejs\node.exe" "C:\Users\Jack Krueger\WebstormProjects\AmazingPhotoApp\webServer.js"
Listening at http://localhost:3000 exporting the directory C:\Users\Jack Krueger\WebstormProjects\AmazingPhotoApp
/test called with param1 =  counts
MongooseError: Model.countDocuments() no longer accepts a callback
    at Function.countDocuments (C:\Users\Jack Krueger\WebstormProjects\AmazingPhotoApp\node_modules\mongoose\lib\model.js:2253:11)
    at C:\Users\Jack Krueger\WebstormProjects\AmazingPhotoApp\webServer.js:106:28
    at C:\Users\Jack Krueger\WebstormProjects\AmazingPhotoApp\node_modules\async\dist\async.js:2588:44
    at eachOfArrayLike (C:\Users\Jack Krueger\WebstormProjects\AmazingPhotoApp\node_modules\async\dist\async.js:506:13)
    at eachOf (C:\Users\Jack Krueger\WebstormProjects\AmazingPhotoApp\node_modules\async\dist\async.js:626:16)
    at awaitable (C:\Users\Jack Krueger\WebstormProjects\AmazingPhotoApp\node_modules\async\dist\async.js:211:32)
    at Object.eachLimit (C:\Users\Jack Krueger\WebstormProjects\AmazingPhotoApp\node_modules\async\dist\async.js:2691:16)
    at Object.awaitable (C:\Users\Jack Krueger\WebstormProjects\AmazingPhotoApp\node_modules\async\dist\async.js:211:32)
    at C:\Users\Jack Krueger\WebstormProjects\AmazingPhotoApp\webServer.js:105:15
    at Layer.handle [as handle_request] (C:\Users\Jack Krueger\WebstormProjects\AmazingPhotoApp\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\Jack Krueger\WebstormProjects\AmazingPhotoApp\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (C:\Users\Jack Krueger\WebstormProjects\AmazingPhotoApp\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (C:\Users\Jack Krueger\WebstormProjects\AmazingPhotoApp\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\Jack Krueger\WebstormProjects\AmazingPhotoApp\node_modules\express\lib\router\index.js:284:15
    at param (C:\Users\Jack Krueger\WebstormProjects\AmazingPhotoApp\node_modules\express\lib\router\index.js:365:14)
    at param (C:\Users\Jack Krueger\WebstormProjects\AmazingPhotoApp\node_modules\express\lib\router\index.js:376:14)
/test called with param1 =  info
MongooseError: Model.find() no longer accepts a callback
    at Function.find (C:\Users\Jack Krueger\WebstormProjects\AmazingPhotoApp\node_modules\mongoose\lib\model.js:2100:11)
    at C:\Users\Jack Krueger\WebstormProjects\AmazingPhotoApp\webServer.js:76:20
    at Layer.handle [as handle_request] (C:\Users\Jack Krueger\WebstormProjects\AmazingPhotoApp\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\Jack Krueger\WebstormProjects\AmazingPhotoApp\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (C:\Users\Jack Krueger\WebstormProjects\AmazingPhotoApp\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (C:\Users\Jack Krueger\WebstormProjects\AmazingPhotoApp\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\Jack Krueger\WebstormProjects\AmazingPhotoApp\node_modules\express\lib\router\index.js:284:15
    at param (C:\Users\Jack Krueger\WebstormProjects\AmazingPhotoApp\node_modules\express\lib\router\index.js:365:14)
    at param (C:\Users\Jack Krueger\WebstormProjects\AmazingPhotoApp\node_modules\express\lib\router\index.js:376:14)
    at Function.process_params (C:\Users\Jack Krueger\WebstormProjects\AmazingPhotoApp\node_modules\express\lib\router\index.js:421:3)
    at next (C:\Users\Jack Krueger\WebstormProjects\AmazingPhotoApp\node_modules\express\lib\router\index.js:280:10)
    at SendStream.error (C:\Users\Jack Krueger\WebstormProjects\AmazingPhotoApp\node_modules\serve-static\index.js:121:7)
    at SendStream.emit (node:events:514:28)
    at SendStream.error (C:\Users\Jack Krueger\WebstormProjects\AmazingPhotoApp\node_modules\send\index.js:270:17)
    at SendStream.onStatError (C:\Users\Jack Krueger\WebstormProjects\AmazingPhotoApp\node_modules\send\index.js:417:12)
    at next (C:\Users\Jack Krueger\WebstormProjects\AmazingPhotoApp\node_modules\send\index.js:731:16)


``` 

</p>
</details>

**Comment by btdobbs** [comment]
Similar to #4 and #6, your project 6 repo needs to be updated to the latest changes.  Specifically, this error has to do with package.json  and package-lock.json files.  If you download these files before 2am this morning, the bluebird, mongoose, etc files were not listed.  It's important that the locked version is used.  Otherwise, you will get the latest version which has breaking changes with the existing code (see [this](https://mongoosejs.com/docs/migrating_to_7.html#dropped-callback-support) mongoose migrating to version 7 link).  Note, the locked version of mongoose is ^6.2.1 as documented in the package and package.lock files.
